name: publish
on: [push]
publish-exporter-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the falco exporter Docker image
run: |
       docker build . --tag ghcr.io/SirCocas/falco-exporter-custom-client:latest
       docker run ghcr.io/SirCocas/falco-exporter-custom-client:latest
       docker push ghcr.io/SirCocas/falco-exporter-custom-client:latest